HEROS = ['axe', 'earthshaker', 'pudge', 'sand_king', 'sven', 'tiny', 'kunkka', 'slardar', 'tidehunter', 'beastmaster',
         'wraith_king', 'dragon_knight', 'clockwerk', 'lifestealer', 'omniknight', 'huskar', 'night_stalker', 'doom',
         'spirit_breaker', 'alchemist', 'lycan', 'brewmaster', 'chaos_knight', 'treant_protector', 'undying', 'io',
         'centaur_warrunner', 'magnus', 'timbersaw', 'bristleback', 'tusk', 'abaddon', 'elder_titan',
         'legion_commander', 'earth_spirit', 'underlord', 'phoenix', 'anti-mage', 'bloodseeker', 'drow_ranger',
         'juggernaut', 'mirana', 'morphling', 'shadow_fiend', 'phantom_lancer', 'razor', 'vengeful_spirit', 'riki',
         'sniper', 'venomancer', 'faceless_void', 'phantom_assassin', 'templar_assassin', 'viper', 'luna', 'clinkz',
         'broodmother', 'bounty_hunter', 'weaver', 'spectre', 'ursa', 'gyrocopter', 'lone_druid', 'meepo',
         'nyx_assassin', 'naga_siren', 'slark', 'medusa', 'troll_warlord', 'ember_spirit', 'terrorblade', 'arc_warden',
         'monkey_king', 'bane', 'crystal_maiden', 'puck', 'storm_spirit', 'windranger', 'zeus', 'lina', 'lion',
         'shadow_shaman', 'witch_doctor', 'lich', 'enigma', 'tinker', 'necrophos', 'warlock', 'queen_of_pain',
         'death_prophet', 'pugna', 'dazzle', 'leshrac', 'natures_prophet', 'dark_seer', 'enchantress', 'jakiro',
         'batrider', 'chen', 'ancient_apparition', 'invoker', 'silencer', 'outworld_devourer', 'shadow_demon',
         'ogre_magi', 'rubick', 'disruptor', 'keeper_of_the_light', 'visage', 'skywrath_mage', 'techies', 'oracle',
         'winter_wyvern']
HEROS_CN = {'axe': '斧王', 'earthshaker': '撼地者', 'pudge': '帕吉', 'sand_king': '沙王', 'sven': '斯温', 'tiny': '小小',
            'kunkka': '昆卡', 'slardar': '斯拉达', 'tidehunter': '潮汐猎人', 'beastmaster': '兽王', 'wraith_king': '冥魂大帝',
            'dragon_knight': '龙骑士', 'clockwerk': '发条技师', 'lifestealer': '噬魂鬼', 'omniknight': '全能骑士', 'huskar': '哈斯卡',
            'night_stalker': '暗夜魔王', 'doom': '末日使者', 'spirit_breaker': '裂魂人', 'alchemist': '炼金术士', 'lycan': '狼人',
            'brewmaster': '酒仙', 'chaos_knight': '混沌骑士', 'treant_protector': '树精卫士', 'undying': '不朽尸王', 'io': '艾欧',
            'centaur_warrunner': '半人马战行者', 'magnus': '马格纳斯', 'timbersaw': '伐木机', 'bristleback': '钢背兽', 'tusk': '巨牙海民',
            'abaddon': '亚巴顿', 'elder_titan': '上古巨神', 'legion_commander': '军团指挥官', 'earth_spirit': '大地之灵',
            'underlord': '孽主', 'phoenix': '凤凰', 'anti-mage': '敌法师', 'bloodseeker': '嗜血狂魔', 'drow_ranger': '卓尔游侠',
            'juggernaut': '主宰', 'mirana': '米拉娜', 'morphling': '变体精灵', 'shadow_fiend': '影魔', 'phantom_lancer': '幻影长矛手',
            'razor': '剃刀', 'vengeful_spirit': '复仇之魂', 'riki': '力丸', 'sniper': '狙击手', 'venomancer': '剧毒术士',
            'faceless_void': '虚空假面', 'phantom_assassin': '幻影刺客', 'templar_assassin': '圣堂刺客', 'viper': '冥界亚龙',
            'luna': '露娜', 'clinkz': '克林克兹',
            'broodmother': '育母蜘蛛', 'bounty_hunter': '赏金猎人', 'weaver': '编织者', 'spectre': '幽鬼', 'ursa': '熊战士',
            'gyrocopter': '矮人直升机', 'lone_druid': '德鲁伊', 'meepo': '米波', 'nyx_assassin': '司夜刺客', 'naga_siren': '娜迦海妖',
            'slark': '斯拉克', 'medusa': '美杜莎', 'troll_warlord': '巨魔战将', 'ember_spirit': '灰烬之灵', 'terrorblade': '恐怖利刃',
            'arc_warden': '天穹守望者', 'monkey_king': '齐天大圣', 'bane': '祸乱之源', 'crystal_maiden': '水晶室女', 'puck': '帕克',
            'storm_spirit': '风暴之灵', 'windranger': '风行者', 'zeus': '宙斯', 'lina': '莉娜', 'lion': '莱恩',
            'shadow_shaman': '暗影萨满', 'witch_doctor': '巫医', 'lich': '巫妖', 'enigma': '谜团', 'tinker': '修补匠',
            'necrophos': '瘟疫法师', 'warlock': '术士', 'queen_of_pain': '痛苦女王', 'death_prophet': '死亡先知', 'pugna': '帕格纳',
            'dazzle': '戴泽', 'leshrac': '拉席克', 'natures_prophet': '先知', 'dark_seer': '黑暗贤者', 'enchantress': '魅惑魔女',
            'jakiro': '杰奇洛', 'batrider': '蝙蝠骑士', 'chen': '陈', 'ancient_apparition': '远古冰魄', 'invoker': '祈求者',
            'silencer': '沉默术士', 'outworld_devourer': '殁境神蚀者', 'shadow_demon': '暗影恶魔', 'ogre_magi': '食人魔魔法师',
            'rubick': '拉比克', 'disruptor': '干扰者', 'keeper_of_the_light': '光之守卫', 'visage': '维萨吉',
            'skywrath_mage': '天怒法师', 'techies': '工程师', 'oracle': '神谕者', 'winter_wyvern': '寒冬飞龙'}
HEROS_EN = {'axe': 'Axe', 'earthshaker': 'Earthshaker', 'pudge': 'Pudge', 'sand_king': 'Sand King', 'sven': 'Sven',
            'tiny': 'Tiny', 'kunkka': 'Kunkka', 'slardar': 'Slardar', 'tidehunter': 'Tidehunter',
            'beastmaster': 'Beastmaster', 'wraith_king': 'Wraith King', 'dragon_knight': 'Dragon Knight',
            'clockwerk': 'Clockwerk', 'lifestealer': 'Lifestealer', 'omniknight': 'Omniknight', 'huskar': 'Huskar',
            'night_stalker': 'Night Stalker', 'doom': 'Doom', 'spirit_breaker': 'Spirit Breaker',
            'alchemist': 'Alchemist', 'lycan': 'Lycan', 'brewmaster': 'Brewmaster', 'chaos_knight': 'Chaos Knight',
            'treant_protector': 'Treant Protector', 'undying': 'Undying', 'io': 'Io',
            'centaur_warrunner': 'Centaur Warrunner', 'magnus': 'Magnus', 'timbersaw': 'Timbersaw',
            'bristleback': 'Bristleback', 'tusk': 'Tusk', 'abaddon': 'Abaddon', 'elder_titan': 'Elder Titan',
            'legion_commander': 'Legion Commander', 'earth_spirit': 'Earth Spirit', 'underlord': 'Underlord',
            'phoenix': 'Phoenix', 'anti-mage': 'Anti-Mage', 'bloodseeker': 'Bloodseeker', 'drow_ranger': 'Drow Ranger',
            'juggernaut': 'Juggernaut', 'mirana': 'Mirana', 'morphling': 'Morphling', 'shadow_fiend': 'Shadow Fiend',
            'phantom_lancer': 'Phantom Lancer', 'razor': 'Razor', 'vengeful_spirit': 'Vengeful Spirit', 'riki': 'Riki',
            'sniper': 'Sniper', 'venomancer': 'Venomancer', 'faceless_void': 'Faceless Void',
            'phantom_assassin': 'Phantom Assassin', 'templar_assassin': 'Templar Assassin', 'viper': 'Viper',
            'luna': 'Luna', 'clinkz': 'Clinkz',
            'broodmother': 'Broodmother', 'bounty_hunter': 'Bounty Hunter', 'weaver': 'Weaver', 'spectre': 'Spectre',
            'ursa': 'Ursa', 'gyrocopter': 'Gyrocopter', 'lone_druid': 'Lone Druid', 'meepo': 'Meepo',
            'nyx_assassin': 'Nyx Assassin', 'naga_siren': 'Naga Siren', 'slark': 'Slark', 'medusa': 'Medusa',
            'troll_warlord': 'Troll Warlord', 'ember_spirit': 'Ember Spirit', 'terrorblade': 'Terrorblade',
            'arc_warden': 'Arc Warden', 'monkey_king': 'Monkey King', 'bane': 'Bane',
            'crystal_maiden': 'Crystal Maiden', 'puck': 'Puck', 'storm_spirit': 'Storm Spirit',
            'windranger': 'Windranger', 'zeus': 'Zeus', 'lina': 'Lina', 'lion': 'Lion',
            'shadow_shaman': 'Shadow Shaman', 'witch_doctor': 'Witch Doctor', 'lich': 'Lich', 'enigma': 'Enigma',
            'tinker': 'Tinker', 'necrophos': 'Necrophos', 'warlock': 'Warlock', 'queen_of_pain': 'Queen of Pain',
            'death_prophet': 'Death Prophet', 'pugna': 'Pugna', 'dazzle': 'Dazzle', 'leshrac': 'Leshrac',
            'natures_prophet': 'Natures Prophet', 'dark_seer': 'Dark Seer', 'enchantress': 'Enchantress',
            'jakiro': 'Jakiro', 'batrider': 'Batrider', 'chen': 'Chen', 'ancient_apparition': 'Ancient Apparition',
            'invoker': 'Invoker', 'silencer': 'Silencer', 'outworld_devourer': 'Outworld Devourer',
            'shadow_demon': 'Shadow Demon', 'ogre_magi': 'Ogre Magi', 'rubick': 'Rubick', 'disruptor': 'Disruptor',
            'keeper_of_the_light': 'Keeper of the Light', 'visage': 'Visage', 'skywrath_mage': 'Skywrath Mage',
            'techies': 'Techies', 'oracle': 'Oracle', 'winter_wyvern': 'Winter Wyvern'}
HEROS_TYPE = {'axe': 'str', 'earthshaker': 'str', 'pudge': 'str', 'sand_king': 'str', 'sven': 'str', 'tiny': 'str',
              'kunkka': 'str', 'slardar': 'str', 'tidehunter': 'str', 'beastmaster': 'str', 'wraith_king': 'str',
              'dragon_knight': 'str', 'clockwerk': 'str', 'lifestealer': 'str', 'omniknight': 'str', 'huskar': 'str',
              'night_stalker': 'str', 'doom': 'str', 'spirit_breaker': 'str', 'alchemist': 'str', 'lycan': 'str',
              'brewmaster': 'str', 'chaos_knight': 'str', 'treant_protector': 'str', 'undying': 'str', 'io': 'str',
              'centaur_warrunner': 'str', 'magnus': 'str', 'timbersaw': 'str', 'bristleback': 'str', 'tusk': 'str',
              'abaddon': 'str', 'elder_titan': 'str', 'legion_commander': 'str', 'earth_spirit': 'str',
              'underlord': 'str', 'phoenix': 'str', 'anti-mage': 'agi', 'bloodseeker': 'agi', 'drow_ranger': 'agi',
              'juggernaut': 'agi', 'mirana': 'agi', 'morphling': 'agi', 'shadow_fiend': 'agi', 'phantom_lancer': 'agi',
              'razor': 'agi', 'vengeful_spirit': 'agi', 'riki': 'agi', 'sniper': 'agi', 'venomancer': 'agi',
              'faceless_void': 'agi', 'phantom_assassin': 'agi', 'templar_assassin': 'agi', 'viper': 'agi',
              'luna': 'agi', 'clinkz': 'agi',
              'broodmother': 'agi', 'bounty_hunter': 'agi', 'weaver': 'agi', 'spectre': 'agi', 'ursa': 'agi',
              'gyrocopter': 'agi', 'lone_druid': 'agi', 'meepo': 'agi', 'nyx_assassin': 'agi', 'naga_siren': 'agi',
              'slark': 'agi', 'medusa': 'agi', 'troll_warlord': 'agi', 'ember_spirit': 'agi', 'terrorblade': 'agi',
              'arc_warden': 'agi', 'monkey_king': 'agi', 'bane': 'int', 'crystal_maiden': 'int', 'puck': 'int',
              'storm_spirit': 'int', 'windranger': 'int', 'zeus': 'int', 'lina': 'int', 'lion': 'int',
              'shadow_shaman': 'int', 'witch_doctor': 'int', 'lich': 'int', 'enigma': 'int', 'tinker': 'int',
              'necrophos': 'int', 'warlock': 'int', 'queen_of_pain': 'int', 'death_prophet': 'int', 'pugna': 'int',
              'dazzle': 'int', 'leshrac': 'int', 'natures_prophet': 'int', 'dark_seer': 'int', 'enchantress': 'int',
              'jakiro': 'int', 'batrider': 'int', 'chen': 'int', 'ancient_apparition': 'int', 'invoker': 'int',
              'silencer': 'int', 'outworld_devourer': 'int', 'shadow_demon': 'int', 'ogre_magi': 'int', 'rubick': 'int',
              'disruptor': 'int', 'keeper_of_the_light': 'int', 'visage': 'int', 'skywrath_mage': 'int',
              'techies': 'int', 'oracle': 'int', 'winter_wyvern': 'int'}

CN_HEROS = {'斧王': 'axe', '撼地者': 'earthshaker', '帕吉': 'pudge', '沙王': 'sand_king', '斯温': 'sven', '小小': 'tiny',
            '昆卡': 'kunkka', '斯拉达': 'slardar', '潮汐猎人': 'tidehunter', '兽王': 'beastmaster', '冥魂大帝': 'wraith_king',
            '龙骑士': 'dragon_knight', '发条技师': 'clockwerk', '噬魂鬼': 'lifestealer', '全能骑士': 'omniknight', '哈斯卡': 'huskar',
            '暗夜魔王': 'night_stalker', '末日使者': 'doom', '裂魂人': 'spirit_breaker', '炼金术士': 'alchemist', '狼人': 'lycan',
            '酒仙': 'brewmaster', '混沌骑士': 'chaos_knight', '树精卫士': 'treant_protector', '不朽尸王': 'undying', '艾欧': 'io',
            '半人马战行者': 'centaur_warrunner', '马格纳斯': 'magnus', '伐木机': 'timbersaw', '钢背兽': 'bristleback', '巨牙海民': 'tusk',
            '亚巴顿': 'abaddon', '上古巨神': 'elder_titan', '军团指挥官': 'legion_commander', '大地之灵': 'earth_spirit',
            '孽主': 'underlord', '凤凰': 'phoenix', '敌法师': 'anti-mage', '嗜血狂魔': 'bloodseeker', '卓尔游侠': 'drow_ranger',
            '主宰': 'juggernaut', '米拉娜': 'mirana', '变体精灵': 'morphling', '影魔': 'shadow_fiend', '幻影长矛手': 'phantom_lancer',
            '剃刀': 'razor', '复仇之魂': 'vengeful_spirit', '力丸': 'riki', '狙击手': 'sniper', '剧毒术士': 'venomancer',
            '虚空假面': 'faceless_void', '幻影刺客': 'phantom_assassin', '圣堂刺客': 'templar_assassin', '冥界亚龙': 'viper',
            '露娜': 'luna', '克林克兹': 'clinkz',
            '育母蜘蛛': 'broodmother', '赏金猎人': 'bounty_hunter', '编织者': 'weaver', '幽鬼': 'spectre', '熊战士': 'ursa',
            '矮人直升机': 'gyrocopter', '德鲁伊': 'lone_druid', '米波': 'meepo', '司夜刺客': 'nyx_assassin', '娜迦海妖': 'naga_siren',
            '斯拉克': 'slark', '美杜莎': 'medusa', '巨魔战将': 'troll_warlord', '灰烬之灵': 'ember_spirit', '恐怖利刃': 'terrorblade',
            '天穹守望者': 'arc_warden', '齐天大圣': 'monkey_king', '祸乱之源': 'bane', '水晶室女': 'crystal_maiden', '帕克': 'puck',
            '风暴之灵': 'storm_spirit', '风行者': 'windranger', '宙斯': 'zeus', '莉娜': 'lina', '莱恩': 'lion',
            '暗影萨满': 'shadow_shaman', '巫医': 'witch_doctor', '巫妖': 'lich', '谜团': 'enigma', '修补匠': 'tinker',
            '瘟疫法师': 'necrophos', '术士': 'warlock', '痛苦女王': 'queen_of_pain', '死亡先知': 'death_prophet', '帕格纳': 'pugna',
            '戴泽': 'dazzle', '拉席克': 'leshrac', '先知': 'natures_prophet', '黑暗贤者': 'dark_seer', '魅惑魔女': 'enchantress',
            '杰奇洛': 'jakiro', '蝙蝠骑士': 'batrider', '陈': 'chen', '远古冰魄': 'ancient_apparition', '祈求者': 'invoker',
            '沉默术士': 'silencer', '殁境神蚀者': 'outworld_devourer', '暗影恶魔': 'shadow_demon', '食人魔魔法师': 'ogre_magi',
            '拉比克': 'rubick', '干扰者': 'disruptor', '光之守卫': 'keeper_of_the_light', '维萨吉': 'visage',
            '天怒法师': 'skywrath_mage', '工程师': 'techies', '神谕者': 'oracle', '寒冬飞龙': 'winter_wyvern'}

EN_HEROS = {'Axe': 'axe', 'Earthshaker': 'earthshaker', 'Pudge': 'pudge', 'Sand King': 'sand_king', 'Sven': 'sven',
            'Tiny': 'tiny', 'Kunkka': 'kunkka', 'Slardar': 'slardar', 'Tidehunter': 'tidehunter',
            'Beastmaster': 'beastmaster', 'Wraith King': 'wraith_king', 'Dragon Knight': 'dragon_knight',
            'Clockwerk': 'clockwerk', 'Lifestealer': 'lifestealer', 'Omniknight': 'omniknight', 'Huskar': 'huskar',
            'Night Stalker': 'night_stalker', 'Doom': 'doom', 'Spirit Breaker': 'spirit_breaker',
            'Alchemist': 'alchemist', 'Lycan': 'lycan', 'Brewmaster': 'brewmaster', 'Chaos Knight': 'chaos_knight',
            'Treant Protector': 'treant_protector', 'Undying': 'undying', 'Io': 'io',
            'Centaur Warrunner': 'centaur_warrunner', 'Magnus': 'magnus', 'Timbersaw': 'timbersaw',
            'Bristleback': 'bristleback', 'Tusk': 'tusk', 'Abaddon': 'abaddon', 'Elder Titan': 'elder_titan',
            'Legion Commander': 'legion_commander', 'Earth Spirit': 'earth_spirit', 'Underlord': 'underlord',
            'Phoenix': 'phoenix', 'Anti-Mage': 'anti-mage', 'Bloodseeker': 'bloodseeker', 'Drow Ranger': 'drow_ranger',
            'Juggernaut': 'juggernaut', 'Mirana': 'mirana', 'Morphling': 'morphling', 'Shadow Fiend': 'shadow_fiend',
            'Phantom Lancer': 'phantom_lancer', 'Razor': 'razor', 'Vengeful Spirit': 'vengeful_spirit', 'Riki': 'riki',
            'Sniper': 'sniper', 'Venomancer': 'venomancer', 'Faceless Void': 'faceless_void',
            'Phantom Assassin': 'phantom_assassin', 'Templar Assassin': 'templar_assassin', 'Viper': 'viper',
            'Luna': 'luna', 'Clinkz': 'clinkz',
            'Broodmother': 'broodmother', 'Bounty Hunter': 'bounty_hunter', 'Weaver': 'weaver', 'Spectre': 'spectre',
            'Ursa': 'ursa', 'Gyrocopter': 'gyrocopter', 'Lone Druid': 'lone_druid', 'Meepo': 'meepo',
            'Nyx Assassin': 'nyx_assassin', 'Naga Siren': 'naga_siren', 'Slark': 'slark', 'Medusa': 'medusa',
            'Troll Warlord': 'troll_warlord', 'Ember Spirit': 'ember_spirit', 'Terrorblade': 'terrorblade',
            'Arc Warden': 'arc_warden', 'Monkey King': 'monkey_king', 'Bane': 'bane',
            'Crystal Maiden': 'crystal_maiden', 'Puck': 'puck', 'Storm Spirit': 'storm_spirit',
            'Windranger': 'windranger', 'Zeus': 'zeus', 'Lina': 'lina', 'Lion': 'lion',
            'Shadow Shaman': 'shadow_shaman', 'Witch Doctor': 'witch_doctor', 'Lich': 'lich', 'Enigma': 'enigma',
            'Tinker': 'tinker', 'Necrophos': 'necrophos', 'Warlock': 'warlock', 'Queen of Pain': 'queen_of_pain',
            'Death Prophet': 'death_prophet', 'Pugna': 'pugna', 'Dazzle': 'dazzle', 'Leshrac': 'leshrac',
            'Natures Prophet': 'natures_prophet', 'Dark Seer': 'dark_seer', 'Enchantress': 'enchantress',
            'Jakiro': 'jakiro', 'Batrider': 'batrider', 'Chen': 'chen', 'Ancient Apparition': 'ancient_apparition',
            'Invoker': 'invoker', 'Silencer': 'silencer', 'Outworld Devourer': 'outworld_devourer',
            'Shadow Demon': 'shadow_demon', 'Ogre Magi': 'ogre_magi', 'Rubick': 'rubick', 'Disruptor': 'disruptor',
            'Keeper of the Light': 'keeper_of_the_light', 'Visage': 'visage', 'Skywrath Mage': 'skywrath_mage',
            'Techies': 'techies', 'Oracle': 'oracle', 'Winter Wyvern': 'winter_wyvern'}

STR_HEROS = ['axe', 'earthshaker', 'pudge', 'sand_king', 'sven', 'tiny', 'kunkka', 'slardar', 'tidehunter',
             'beastmaster', 'wraith_king', 'dragon_knight', 'clockwerk', 'lifestealer', 'omniknight', 'huskar',
             'night_stalker', 'doom', 'spirit_breaker',
             'alchemist', 'lycan', 'brewmaster', 'chaos_knight', 'treant_protector', 'undying', 'io',
             'centaur_warrunner', 'magnus', 'timbersaw', 'bristleback', 'tusk', 'abaddon', 'elder_titan',
             'legion_commander', 'earth_spirit', 'underlord', 'phoenix']
AGI_HEROS = ['anti-mage', 'bloodseeker', 'drow_ranger', 'juggernaut', 'mirana', 'morphling', 'shadow_fiend',
             'phantom_lancer', 'razor', 'vengeful_spirit', 'riki', 'sniper', 'venomancer', 'faceless_void',
             'phantom_assassin', 'templar_assassin',
             'viper', 'luna', 'clinkz', 'broodmother', 'bounty_hunter', 'weaver', 'spectre', 'ursa', 'gyrocopter',
             'lone_druid', 'meepo', 'nyx_assassin', 'naga_siren', 'slark', 'medusa', 'troll_warlord', 'ember_spirit',
             'terrorblade', 'arc_warden', 'monkey_king']
INT_HEROS = ['bane', 'crystal_maiden', 'puck', 'storm_spirit', 'windranger', 'zeus', 'lina', 'lion', 'shadow_shaman',
             'witch_doctor', 'lich', 'enigma', 'tinker', 'necrophos', 'warlock', 'queen_of_pain', 'death_prophet',
             'pugna', 'dazzle', 'leshrac', 'natures_prophet',
             'dark_seer', 'enchantress', 'jakiro', 'batrider', 'chen', 'ancient_apparition', 'invoker', 'silencer',
             'outworld_devourer', 'shadow_demon', 'ogre_magi', 'rubick', 'disruptor', 'keeper_of_the_light', 'visage',
             'skywrath_mage', 'techies', 'oracle', 'winter_wyvern']

IMAGE_PATH = 'C:\\Users\\ieatk\\Documents\\Coding\\Dota2BanPicks\\images'

IMAGES = dict(zip(HEROS, map(lambda hero: IMAGE_PATH + 'normal\\' + hero + '.png', HEROS)))
IMAGES['unknown'] = IMAGE_PATH + 'normal\\unknown.png'
IMAGES_GRAY = dict(zip(HEROS, map(lambda hero: IMAGE_PATH + 'mono\\' + hero + '.png', HEROS)))
